In [1]:
import numpy as np

In [2]:
import numpy as np
X_test = np.load("X_test.npy")
y_test = np.load("y_test.npy")
person_train_valid = np.load("person_train_valid.npy")
X_train_valid = np.load("X_train_valid.npy")
y_train_valid = np.load("y_train_valid.npy")
person_test = np.load("person_test.npy")


### Shape of data

In [3]:
print ('Training/Valid data shape: {}'.format(X_train_valid.shape))
print ('Test data shape: {}'.format(X_test.shape))
print ('Training/Valid target shape: {}'.format(y_train_valid.shape))
print ('Test target shape: {}'.format(y_test.shape))
print ('Person train/valid shape: {}'.format(person_train_valid.shape))
print ('Person test shape: {}'.format(person_test.shape))


Training/Valid data shape: (2115, 22, 1000)
Test data shape: (443, 22, 1000)
Training/Valid target shape: (2115,)
Test target shape: (443,)
Person train/valid shape: (2115, 1)
Person test shape: (443, 1)


In [4]:
import pandas as pd

In [9]:
X_train_valid.shape

(2115, 22, 1000)

In [11]:
y_train_valid

array([771, 772, 769, ..., 772, 772, 771], dtype=int32)

In [13]:
48*6*4

1152

In [17]:
2115+443

2558

In [18]:
443/9

49.22222222222222

In [22]:
np.unique(person_train_valid)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

## How the data is structured

The training data has 2115 instances of sample points from 22 difference electrodes. Data from each electrode is recorded for 1000 time steps. Hence the training data shape is given as 2115x20x1000. Note that there are a total of 9 subjects used while capturing this data. 

The person_train_valid provides the id of the subject used for training this data. This runs from 0-8. 

**Note** - From the project guidelines 

1. Optimize the classification accuracy for subject 1. Does it help to train across all subjects?

   a. Here first train all classifiers on just subject 1 data and test. 
   b. Next train on all data and check. 
   c. Provide accuracy details across all models across both cases for subject one. 
   
2. Optimize the classification accuracy across all subjects. How does the classifier do? Do you
    notice any interesting trends?
    
    a. Perform the above except across classes. 
    
3. Evaluate the classification accuracy as a function of time (e.g., does it increase as you have data over longer periods of time? how much time is required to get a reasonable classification accuracy?)

    a. Vary the time steps taken into consideration, obviously causality has to be preserved. i.e cant use future time steps to look at values in the past

In [23]:
values, counts = np.unique(person_train_valid, return_counts=True)

In [24]:
values

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [25]:
counts

array([237, 236, 236, 234, 235, 236, 238, 232, 231])

The values for person seem to be more or less evenly split 